In [12]:
import numpy as np
import pandas as pd
import os

In [13]:
new_cols = [
'gr_first_name',
'gr_last_name',
'test_record_num',
'pt_record_num',
'date_time_of_test',
'distance',
'ambulation_time',
'velocity',
'step_count',
'cadence',
'step_time_sec_left',
'step_length_cm_left',
'step_time_sec_right',
'step_length_cm_right',
'step_extremity_ratio_left',
'step_extremity_ratio_right',
'cycle_time_sec_left',
'cycle_time_sec_right',
'stride_length_cm_left',
'stride_length_cm_right',
'hh_base_support_cm_left',
'hh_base_support_cm_right',
'swing_pct_of_cycle_left',
'swing_pct_of_cycle_right',
'swing_time_sec_left',
'swing_time_sec_right',
'stance_pct_of_cycle_left',
'stance_pct_of_cycle_right',
'stance_time_sec_left',
'stance_time_sec_right',
'sgl_supp_pct_cycle_lt',
'sgl_supp_pct_cycle_rt',
'sgl_supp_time_sec_lt',
'sgl_supp_time_sec_rt',
'dbl_supp_pct_cycle_lt',
'dbl_supp_pct_cycle_rt',
'dbl_supp_time_sec_lt',
'dbl_supp_time_sec_rt',
'step_time_differential',
'step_length_differetial',
'cycle_time_differential',
'functional_amb_profile',
'treatment_count',
'footfalls',
'comments',
'normalized_velocity',
'leg_length_cm_left',
'leg_length_cm_right',
'number_of_passes',
'ambulatory_devices',
'ambulatory_aids',
'user',
'toe_in_out_left',
'toe_in_out_right',
'heel_off_on_time_left',
'heel_off_on_time_right',
'heel_off_on_perc_left',
'heel_off_on_perc_right',
'dbl_supp_load_time_lt',
'dbl_supp_load_time_rt',
'dbl_supp_load_pct_gc_lt',
'dbl_supp_load_pct_gc_rt',
'dbl_supp_unload_time_lt',
'dbl_supp_unload_time_rt',
'dbl_supp_unload_pct_gc_lt',
'dbl_supp_unload_pct_gc_rt',
'asst_ortho_etc_1',
'asst_ortho_etc_2',
'asst_ortho_etc_3',
'asst_ortho_etc_4',
'asst_ortho_etc_5',
'type_of_test',
'software_version',
'number_of_pads',
'normal_group_code',
'standard_walk_steps',
'standard_amb_time',
'stride_velocity_left',
'stride_velocity_right',
'shoe_flag',
'expected_foot_length',
'expected_foot_width',
'foot_length_left',
'foot_width_left',
'foot_length_right',
'foot_width_right',
'step_len_std_dev_lt',
'step_len_std_dev_rt',
'step_time_std_dev_lt',
'step_time_std_dev_rt',
'str_len_std_dev_left',
'str_len_std_dev_rt',
'str_time_std_dev_lt',
'str_time_std_dev_rt',
'swing_time_std_dev_left',
'swing_time_std_dev_right',
'stance_time_std_dev_left',
'stance_time_std_dev_right',
'stride_vel_std_dev_lt',
'stride_vel_std_dev_rt',
'sgl_supp_time_std_dev_lt',
'sgl_supp_time_std_dev_rt',
'dbl_supp_time_std_dev_lt',
'dbl_supp_time_std_dev_rt',
'heel_off_on_std_dev_left',
'heel_off_on_std_dev_right',
'supp_base_std_dev_left',
'supp_base_std_dev_right',
'foot_length_std_dev_left',
'foot_length_std_dev_right',
'foot_width_std_dev_left',
'foot_width_std_dev_right',
'computer_time_msec',
'trigger_1_0',
'trigger_1_1',
'trigger_2_0',
'trigger_2_1',
'trigger_1_e',
'trigger_1_e_1',
'trigger_2_e',
'trigger_2_e_1',
'inclinometer1',
'inclin_avg_tilt_lr',
'inclin_avg_tilt_fb',
'inclin_min_tilt_lr',
'inclin_max_tilt_lr',
'inclin_max_tilt_fb',
'inclin_min_tilt_fb',
'inclin_veloc_tilt_lr',
'inclin_veloc_tilt_fb',
'inclin_sd_tilt_lr',
'inclin_sd_tilt_fb',
'inclinometer2',
'inclin2_avg_tilt_lr',
'inclin2_avg_tilt_fb',
'inclin2_min_tilt_lr',
'inclin2_max_tilt_lr'
]

In [14]:
old_cols = [
'First Name  ',
'Last Name',
'Test Record #',
'Pt Record #',
'Date / Time of Test',
'Distance',
'Ambulation Time',
'Velocity',
'Step Count',
'Cadence',
'Step Time(sec) L',
'Step Length(cm) L',
'Step Time(sec) R',
'Step Length(cm) R',
'Step Extremity(ratio) L',
'Step Extremity(ratio) R',
'Cycle Time(sec) L',
'Cycle Time(sec) R',
'Stride Length(cm) L',
'Stride Length(cm) R',
'HH Base Support (cm) L',
'HH Base Support (cm) R',
'Swing % of Cycle L',
'Swing % of Cycle R',
'Swing Time(sec) L',
'Swing Time(sec) R',
'Stance % of Cycle L',
'Stance % of Cycle R',
'Stance Time(sec)  L',
'Stance Time(sec)  R',
'Single Supp % Cycle L',
'Single Supp % Cycle R',
'Single Supp. Time(sec) L',
'Single Supp. Time(sec) R',
'Double Supp % Cycle L',
'Double Supp % Cycle R',
'Double Supp. Time(sec) L',
'Double Supp. Time(sec) R',
'Step Time Differential',
'Step Length Differential',
'Cycle Time Differential',
'Functional Amb. Profile',
'Treatment Count',
'Footfalls',
'Comments',
'Normalized Velocity  ',
'Leg Length (cm) L',
'Leg Length (cm) R',
'Number of Passes',
'Ambulatory Devices',
'Ambulatory Aids',
'User',
'Toe In / Out L',
'Toe In / Out R',
'Heel Off On Time L',
'Heel Off On Time R',
'Heel Off On Perc L',
'Heel Off On Perc R',
'Double Support Load Time L',
'Double Support Load Time R',
'Double Support Load %GC L',
'Double Support Load %GC R',
'Double Support Unload Time L',
'Double Support Unload Time R',
'Double Support Unload %GC L',
'Double Support Unload %GC R',
'Asst Ortho etc 1',
'Asst Ortho etc  2',
'Asst Ortho etc 3',
'Asst Ortho etc 4',
'Asst Ortho etc 5',
'Type of Test',
'Software Version',
'Number of Pads',
'Normal Group Code',
'Standard Walk Steps',
'Standard Amb Time',
'Stride Velocity Left',
'Stride Velocity Right',
'Shoe Flag',
'Expected Foot Length',
'Expected Foot Width',
'Foot Length Left',
'Foot Width Left',
'Foot Length Right',
'Foot Width Right',
'Step Len Std Dev Left',
'Step Len Std Dev Right',
'Step Time Std Dev Left',
'Step Time Std Dev Right',
'Stride Length Std Dev Left',
'Stride Length Std Dev Right',
'Stride Time Std Dev Left',
'Stride Time Std Dev Right',
'Swing Time Std Dev Left',
'Swing Time Std Dev Right!',
'Stance Time Std Dev Left',
'Stance Time Std Dev Right',
'Stride Velocity Std Dev Left',
'Stride Velocity Std Dev Right',
'Single Supp Time Std Dev Left',
'Single Supp Time Std Dev Right',
'Double Supp Time Std Dev Left',
'Double Supp Time Std Dev Right',
'Heel Off On Std Dev Left',
'Heel Off On Std Dev Right',
'Supp Base Std Dev Left',
'Supp Base Std Dev Right',
'Foot Length Std Dev Left',
'Foot Length Std Dev Right',
'Foot Width Std Dev Left',
'Foot Width Std Dev Right',
'Computer Time (MSec)',
'Trigger 1 0',
'Trigger 1 1',
'Trigger 2 0',
'Trigger 2 1',
'Trigger 1 E',
'Trigger 1 E 1',
'Trigger 2 E',
'Trigger 2 E 1',
'Inclinometer1',
'Inclin_Avg_Tilt_LR',
'Inclin_Avg_Tilt_FB',
'Inclin_Min_Tilt_LR',
'Inclin_Max_Tilt_LR',
'Inclin_Max_Tilt_FB',
'Inclin_Min_Tilt_FB',
'Inclin_Veloc_Tilt_LR',
'Inclin_Veloc_Tilt_FB',
'Inclin_SD_Tilt_LR',
'Inclin_SD_Tilt_FB',
'Inclinometer2',
'Inclin2_Avg_Tilt_LR',
'Inclin2_Avg_Tilt_FB',
'Inclin2_Min_Tilt_LR',
'Inclin2_Max_Tilt_LR'
]

In [15]:
def grGetTestRecords(filename, event_name, instrument, old_columns, new_columns):
    if filename.lower().endswith("csv"):
        df = pd.read_csv(filename, dtype=str) 
    elif filename.lower().endswith("xlsx"):
        df = pd.read_excel(filename, dtype=str)
    else:
        raise RuntimeError("Unknown filetype: " + filename)
        
    dict = {old_columns[i]: new_columns[i] for i in range(len(old_columns))}
    df2 = df[old_columns]
    df3 = df2.rename(columns=dict)
    df4 = df3[~df3['test_record_num'].isna()].copy()
    
    # get FXS id
    last = next(filter(lambda id: not pd.isna(id), df['Last Name']), None)
    if last == None:
        last = 0
        print("WARNING: No FXS ID found.")
    
    # don't forget to add key column
    # TODO: HARD CODED KEY COLUMN NAME study_id
    df4.insert(0, "study_id", last)
    
    # and don't forget to add the 'redcap_repeat_instance' column and its friend 'redcap_event_name'
    # We use 'new' for the redcap_repeat_instance. The event name has to come with the folder name 
    # as input. 
    df4.insert(1, "redcap_event_name", event_name)
    df4.insert(2, "redcap_repeat_instrument", instrument)
    df4.insert(3, "redcap_repeat_instance", "new")
    
    # and insert the filename
    df4.insert(4, 'input_filename', os.path.basename(filename))
    
    # Assign testtype based on contents of 'comments'
    df4.insert(5, 'testtype', 5)
    df4.loc[df4.comments.str.contains("control", na=False), 'testtype'] = 1
    df4.loc[df4.comments.str.contains("light", na=False), 'testtype'] = 2
    df4.loc[df4.comments.str.contains("loaded", na=False), 'testtype'] = 3
    
    return df4

In [16]:
tests = grGetTestRecords('/home/dan/work/rivera-data/500011-138_11_26_19.xlsx', "visit_1_arm_2", "aagrtest", old_cols, new_cols)
# mac tests = grGetTestRecords('/Users/dan/rivera/data/full-single-2.csv', "whatever", old_cols, new_cols)

In [17]:
tests.head()

,study_id,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,input_filename,testtype,gr_first_name,gr_last_name,test_record_num,pt_record_num,...,inclin_min_tilt_fb,inclin_veloc_tilt_lr,inclin_veloc_tilt_fb,inclin_sd_tilt_lr,inclin_sd_tilt_fb,inclinometer2,inclin2_avg_tilt_lr,inclin2_avg_tilt_fb,inclin2_min_tilt_lr,inclin2_max_tilt_lr
0,487,visit_1_arm_2,aagrtest,new,500011-138_11_26_19.xlsx,1,500011-138,487,3,116,...,0,0,0,0,0,0,0,0,0,0
37,487,visit_1_arm_2,aagrtest,new,500011-138_11_26_19.xlsx,2,NaN,NaN,2,NaN,...,0,0,0,0,0,0,0,0,0,0
74,487,visit_1_arm_2,aagrtest,new,500011-138_11_26_19.xlsx,3,NaN,NaN,1,NaN,...,0,0,0,0,0,0,0,0,0,0

In [52]:
tests.loc[tests.comments.str.contains("control", na=False), 'testtype']

0    1
Name: testtype, dtype: int64

In [18]:
tests.to_csv('/home/dan/work/rivera-data/test.csv', index=False)

In [8]:
bigdf = None
# mac 
# folder = '/Users/dan/rivera/tmp'
# linux
folder = '/home/dan/git/GaitRiteCleaner/data/big'
for f in os.scandir(folder):
    if (f.is_file() and f.name.endswith("xlsx")):
        df = grGetTestRecords(os.path.join(folder, f.name), old_cols, new_cols)
        if bigdf is None:
            bigdf = df
        else:
            bigdf = pd.concat((bigdf, df))

In [31]:
#bigdf[bigdf['comments'] != '']
#bigdf['comments']
#s1 = bigdf['comments'].str.lower().str.contains("control")
#s2 = bigdf['comments'].str.lower().str.contains("light")
#s3 = bigdf['comments'].str.lower().str.contains("loaded")
bigdf['testtype'] = 5
bigdf.loc[bigdf.comments.str.contains("control", na=False), 'testtype'] = 1
bigdf.loc[bigdf.comments.str.contains("light", na=False), 'testtype'] = 2
bigdf.loc[bigdf.comments.str.contains("loaded", na=False), 'testtype'] = 3
print( bigdf[bigdf.testtype==5]['comments'].to_low().unique())
#print(np.sum(bigdf.testtype==3))
#print(bigdf.testtype)
#df.loc[df.Age.str.contains("2007"), 'Year'] = 2007
#type(s)
#print(len(s), s.count(), s.isna().count(), s.notna().count())
#s[s.isna()]
#print(   bigdf[bigdf['comments'].str.lower().str.contains("loaded")].comments )

AttributeError: 'Series' object has no attribute 'to_low'

In [110]:
bigdf[bigdf.study_id==75.0]

,study_id,aa_fn,aa_ln,test_record_num,pt_record_num,date_time_of_test,distance,ambulation_time,velocity,step_count,...,inclin_min_tilt_fb,inclin_veloc_tilt_lr,inclin_veloc_tilt_fb,inclin_sd_tilt_lr,inclin_sd_tilt_fb,inclinometer2,inclin2_avg_tilt_lr,inclin2_avg_tilt_fb,inclin2_min_tilt_lr,inclin2_max_tilt_lr
0,75.0,107867-100,75.0,5.0,111.0,2019-11-04 13:37:58,1929.07,12.18,158.4,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,75.0,NaN,NaN,4.0,NaN,2019-11-04 13:40:55,2132.67,14.26,149.6,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66,75.0,NaN,NaN,1.0,NaN,2019-11-04 13:44:47,2161.09,14.18,152.4,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
def is_float(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

In [62]:
def is_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

In [69]:
is_int('1.0')

False

In [11]:
dd=pd.read_csv('GRExportColumns.csv')

In [15]:
print(dd)

                 Export Column      redcap variable name       Value  \
0                  Pt Record #             pt_record_num          96
1            Patient Id Number         patient_id_number
2                    Last Name                 last_name         537
3                 First Name                  first_name  500011-458
4              Leg Length Left           leg_length_left          96
..                         ...                       ...         ...
179                     Toe On                    toe_on       4.059
180                   Toe Off                    toe_off       4.859
181                Heel off/on               heel_off_on       0.083
182    Double Support Loading     double_support_loading           0
183  Double Support Unloading   double_support_unloading           0

    Source data set                     Description  Unnamed: 5  Unnamed: 6  \
0           Patient  GAITRite Patient Record number         NaN         NaN
1           Patient               Patient Id Number         NaN         NaN
2           Patient                       Last Name         NaN         NaN
3           Patient                      First Name         NaN         NaN
4           Patient                 Leg Length Left         NaN         NaN
..              ...                             ...         ...         ...
179          Detail                          Toe On         NaN         NaN
180          Detail                         Toe Off         NaN         NaN
181          Detail                     Heel off/on         NaN         NaN
182          Detail          Double Support Loading         NaN         NaN
183          Detail        Double Support Unloading         NaN         NaN

     Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unnamed: 85  Unnamed: 86  \
0           NaN         NaN         NaN  ...          NaN          NaN
1           NaN         NaN         NaN  ...          NaN          NaN
2           NaN         NaN         NaN  ...          NaN          NaN
3           NaN         NaN         NaN  ...          NaN          NaN
4           NaN         NaN         NaN  ...          NaN          NaN
..          ...         ...         ...  ...          ...          ...
179         NaN         NaN         NaN  ...          NaN          NaN
180         NaN         NaN         NaN  ...          NaN          NaN
181         NaN         NaN         NaN  ...          NaN          NaN
182         NaN         NaN         NaN  ...          NaN          NaN
183         NaN         NaN         NaN  ...          NaN          NaN

     Unnamed: 87  Unnamed: 88  Unnamed: 89  Unnamed: 90  Unnamed: 91  \
0            NaN          NaN          NaN          NaN          NaN
1            NaN          NaN          NaN          NaN          NaN
2            NaN          NaN          NaN          NaN          NaN
3            NaN          NaN          NaN          NaN          NaN
4            NaN          NaN          NaN          NaN          NaN
..           ...          ...          ...          ...          ...
179          NaN          NaN          NaN          NaN          NaN
180          NaN          NaN          NaN          NaN          NaN
181          NaN          NaN          NaN          NaN          NaN
182          NaN          NaN          NaN          NaN          NaN
183          NaN          NaN          NaN          NaN          NaN

     Unnamed: 92  Unnamed: 93  Unnamed: 94
0            NaN          NaN          NaN
1            NaN          NaN          NaN
2            NaN          NaN          NaN
3            NaN          NaN          NaN
4            NaN          NaN          NaN
..           ...          ...          ...
179          NaN          NaN          NaN
180          NaN          NaN          NaN
181          NaN          NaN          NaN
182          NaN          NaN          NaN
183          NaN          NaN          NaN

[184 rows x 95 columns]

In [13]:
datadict=pd.read_csv('datadict.csv')

In [14]:
datadict.head()

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,Identifier?,Branching Logic (Show field only if...),Required Field?,Custom Alignment,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
0,study_id,subject_id_and_consent_date,NaN,text,Study ID Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@HIDDEN-SURVEY
1,dem_trax_subj_id,subject_id_and_consent_date,NaN,text,Subject ID (FXS ID),NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,@HIDDEN-SURVEY
2,dem_trax_date,subject_id_and_consent_date,NaN,text,Date Consent Signed,NaN,MM-DD-YYYY,date_mdy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@HIDDEN-SURVEY
3,rntest,aagrtest,NaN,text,GaitRite Test Record number,NaN,NaN,integer,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
4,testtype,aagrtest,NaN,dropdown,Test type,"1, control | 2, light | 3, loaded",NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN