In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/Users/dan/rivera/data/full-single-2.csv')

In [3]:
df.head()

,Research Reference,Pt Record #,Patient Id Number,Last Name,First Name,Leg Length Left,Leg Length Right,Test Record #,Pt Record #.1,Date / Time of Test,...,Stride Width,Heel On,Heel Off,Mid On,Mid Off,Toe On,Toe Off,Heel off/on,Double Support Loading,Double Support Unloading
0,NaN,104.0,,316.0,108093-100,91.0,91.0,3.0,104.0,9/26/19 15:21,...,0.000,7.225,7.692,7.325,7.825,7.317,7.90,0.092,0.000,0.000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.890,7.784,8.242,7.875,8.359,7.884,8.45,0.083,0.117,0.125
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.034,8.325,8.759,8.409,8.909,8.409,9.00,0.108,0.125,0.133
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.757,8.867,9.375,8.967,9.492,8.975,9.55,0.000,0.133,0.133
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,9.417,9.892,9.509,10.050,9.517,10.10,0.000,0.000,0.000

In [4]:
df[~df['Test Record #'].isna()]

,Research Reference,Pt Record #,Patient Id Number,Last Name,First Name,Leg Length Left,Leg Length Right,Test Record #,Pt Record #.1,Date / Time of Test,...,Stride Width,Heel On,Heel Off,Mid On,Mid Off,Toe On,Toe Off,Heel off/on,Double Support Loading,Double Support Unloading
0,NaN,104.0,,316.0,108093-100,91.0,91.0,3.0,104.0,9/26/19 15:21,...,0.0,7.225,7.692,7.325,7.825,7.317,7.900,0.092,0.0,0.0
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,104.0,9/26/19 15:24,...,0.0,14.959,15.334,15.050,15.550,15.067,15.592,0.141,0.0,0.0
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,104.0,9/26/19 15:27,...,0.0,17.384,17.842,17.467,18.009,17.400,18.059,0.100,0.0,0.0

In [70]:
new_cols = [
'aa_fn',
'aa_ln',
'test_record_num',
'pt_record_num',
'date_time_of_test',
'distance',
'ambulation_time',
'velocity',
'step_count',
'cadence',
'step_time_sec_left',
'step_length_cm_left',
'step_time_sec_right',
'step_length_cm_right',
'step_extremity_ratio_left',
'step_extremity_ratio_right',
'cycle_time_sec_left',
'cycle_time_sec_right',
'stride_length_cm_left',
'stride_length_cm_right',
'hh_base_support_cm_left',
'hh_base_support_cm_right',
'swing_pct_of_cycle_left',
'swing_pct_of_cycle_right',
'swing_time_sec_left',
'swing_time_sec_right',
'stance_pct_of_cycle_left',
'stance_pct_of_cycle_right',
'stance_time_sec_left',
'stance_time_sec_right',
'single_supp_pct_cycle_left',
'single_supp_pct_cycle_right',
'single_supp_time_sec_left',
'single_supp_time_sec_right',
'double_supp_pct_cycle_left',
'double_supp_pct_cycle_right',
'double_supp_time_sec_left',
'double_supp_time_sec_right',
'step_time_differential',
'step_length_differetial',
'cycle_time_differential',
'functional_amb_profile',
'treatment_count',
'footfalls',
'comments',
'normalized_velocity',
'leg_length_cm_left',
'leg_length_cm_right',
'number_of_passes',
'ambulatory_devices',
'ambulatory_aids',
'user',
'toe_in_out_left',
'toe_in_out_right',
'heel_off_on_time_left',
'heel_off_on_time_right',
'heel_off_on_perc_left',
'heel_off_on_perc_right',
'double_support_load_time_left',
'double_support_load_time_right',
'double_support_load_pct_gc_left',
'double_support_load_pct_gc_right',
'double_support_unload_time_left',
'double_support_unload_time_right',
'double_support_unload_pct_gc_left',
'double_support_unload_pct_gc_right',
'asst_ortho_etc_1',
'asst_ortho_etc_2',
'asst_ortho_etc_3',
'asst_ortho_etc_4',
'asst_ortho_etc_5',
'type_of_test',
'software_version',
'number_of_pads',
'normal_group_code',
'standard_walk_steps',
'standard_amb_time',
'stride_velocity_left',
'stride_velocity_right',
'shoe_flag',
'expected_foot_length',
'expected_foot_width',
'foot_length_left',
'foot_width_left',
'foot_length_right',
'foot_width_right',
'step_len_std_dev_left',
'step_len_std_dev_right',
'step_time_std_dev_left',
'step_time_std_dev_right',
'stride_length_std_dev_left',
'stride_length_std_dev_right',
'stride_time_std_dev_left',
'stride_time_std_dev_right',
'swing_time_std_dev_left',
'swing_time_std_dev_right',
'stance_time_std_dev_left',
'stance_time_std_dev_right',
'stride_velocity_std_dev_left',
'stride_velocity_std_dev_right',
'single_supp_time_std_dev_left',
'single_supp_time_std_dev_right',
'double_supp_time_std_dev_left',
'double_supp_time_std_dev_right',
'heel_off_on_std_dev_left',
'heel_off_on_std_dev_right',
'supp_base_std_dev_left',
'supp_base_std_dev_right',
'foot_length_std_dev_left',
'foot_length_std_dev_right',
'foot_width_std_dev_left',
'foot_width_std_dev_right',
'computer_time_msec',
'trigger_1_0',
'trigger_1_1',
'trigger_2_0',
'trigger_2_1',
'trigger_1_e',
'trigger_1_e_1',
'trigger_2_e',
'trigger_2_e_1',
'inclinometer1',
'inclin_avg_tilt_lr',
'inclin_avg_tilt_fb',
'inclin_min_tilt_lr',
'inclin_max_tilt_lr',
'inclin_max_tilt_fb',
'inclin_min_tilt_fb',
'inclin_veloc_tilt_lr',
'inclin_veloc_tilt_fb',
'inclin_sd_tilt_lr',
'inclin_sd_tilt_fb',
'inclinometer2',
'inclin2_avg_tilt_lr',
'inclin2_avg_tilt_fb',
'inclin2_min_tilt_lr',
'inclin2_max_tilt_lr'
]

In [97]:
old_cols = [
'First Name  ',
'Last Name',
'Test Record #',
'Pt Record #',
'Date / Time of Test',
'Distance',
'Ambulation Time',
'Velocity',
'Step Count',
'Cadence',
'Step Time(sec) L',
'Step Length(cm) L',
'Step Time(sec) R',
'Step Length(cm) R',
'Step Extremity(ratio) L',
'Step Extremity(ratio) R',
'Cycle Time(sec) L',
'Cycle Time(sec) R',
'Stride Length(cm) L',
'Stride Length(cm) R',
'HH Base Support (cm) L',
'HH Base Support (cm) R',
'Swing % of Cycle L',
'Swing % of Cycle R',
'Swing Time(sec) L',
'Swing Time(sec) R',
'Stance % of Cycle L',
'Stance % of Cycle R',
'Stance Time(sec)  L',
'Stance Time(sec)  R',
'Single Supp % Cycle L',
'Single Supp % Cycle R',
'Single Supp. Time(sec) L',
'Single Supp. Time(sec) R',
'Double Supp % Cycle L',
'Double Supp % Cycle R',
'Double Supp. Time(sec) L',
'Double Supp. Time(sec) R',
'Step Time Differential',
'Step Length Differential',
'Cycle Time Differential',
'Functional Amb. Profile',
'Treatment Count',
'Footfalls',
'Comments',
'Normalized Velocity  ',
'Leg Length (cm) L',
'Leg Length (cm) R',
'Number of Passes',
'Ambulatory Devices',
'Ambulatory Aids',
'User',
'Toe In / Out L',
'Toe In / Out R',
'Heel Off On Time L',
'Heel Off On Time R',
'Heel Off On Perc L',
'Heel Off On Perc R',
'Double Support Load Time L',
'Double Support Load Time R',
'Double Support Load %GC L',
'Double Support Load %GC R',
'Double Support Unload Time L',
'Double Support Unload Time R',
'Double Support Unload %GC L',
'Double Support Unload %GC R',
'Asst Ortho etc 1',
'Asst Ortho etc  2',
'Asst Ortho etc 3',
'Asst Ortho etc 4',
'Asst Ortho etc 5',
'Type of Test',
'Software Version',
'Number of Pads',
'Normal Group Code',
'Standard Walk Steps',
'Standard Amb Time',
'Stride Velocity Left',
'Stride Velocity Right',
'Shoe Flag',
'Expected Foot Length',
'Expected Foot Width',
'Foot Length Left',
'Foot Width Left',
'Foot Length Right',
'Foot Width Right',
'Step Len Std Dev Left',
'Step Len Std Dev Right',
'Step Time Std Dev Left',
'Step Time Std Dev Right',
'Stride Length Std Dev Left',
'Stride Length Std Dev Right',
'Stride Time Std Dev Left',
'Stride Time Std Dev Right',
'Swing Time Std Dev Left',
'Swing Time Std Dev Right!',
'Stance Time Std Dev Left',
'Stance Time Std Dev Right',
'Stride Velocity Std Dev Left',
'Stride Velocity Std Dev Right',
'Single Supp Time Std Dev Left',
'Single Supp Time Std Dev Right',
'Double Supp Time Std Dev Left',
'Double Supp Time Std Dev Right',
'Heel Off On Std Dev Left',
'Heel Off On Std Dev Right',
'Supp Base Std Dev Left',
'Supp Base Std Dev Right',
'Foot Length Std Dev Left',
'Foot Length Std Dev Right',
'Foot Width Std Dev Left',
'Foot Width Std Dev Right',
'Computer Time (MSec)',
'Trigger 1 0',
'Trigger 1 1',
'Trigger 2 0',
'Trigger 2 1',
'Trigger 1 E',
'Trigger 1 E 1',
'Trigger 2 E',
'Trigger 2 E 1',
'Inclinometer1',
'Inclin_Avg_Tilt_LR',
'Inclin_Avg_Tilt_FB',
'Inclin_Min_Tilt_LR',
'Inclin_Max_Tilt_LR',
'Inclin_Max_Tilt_FB',
'Inclin_Min_Tilt_FB',
'Inclin_Veloc_Tilt_LR',
'Inclin_Veloc_Tilt_FB',
'Inclin_SD_Tilt_LR',
'Inclin_SD_Tilt_FB',
'Inclinometer2',
'Inclin2_Avg_Tilt_LR',
'Inclin2_Avg_Tilt_FB',
'Inclin2_Min_Tilt_LR',
'Inclin2_Max_Tilt_LR'
]

In [98]:
len(old_cols)

137

In [99]:
dict = {old_cols[i]: new_cols[i] for i in range(len(old_cols))}

In [100]:
dict

{'First Name  ': 'aa_fn',
 'Last Name': 'aa_ln',
 'Test Record #': 'test_record_num',
 'Pt Record #': 'pt_record_num',
 'Date / Time of Test': 'date_time_of_test',
 'Distance': 'distance',
 'Ambulation Time': 'ambulation_time',
 'Velocity': 'velocity',
 'Step Count': 'step_count',
 'Cadence': 'cadence',
 'Step Time(sec) L': 'step_time_sec_left',
 'Step Length(cm) L': 'step_length_cm_left',
 'Step Time(sec) R': 'step_time_sec_right',
 'Step Length(cm) R': 'step_length_cm_right',
 'Step Extremity(ratio) L': 'step_extremity_ratio_left',
 'Step Extremity(ratio) R': 'step_extremity_ratio_right',
 'Cycle Time(sec) L': 'cycle_time_sec_left',
 'Cycle Time(sec) R': 'cycle_time_sec_right',
 'Stride Length(cm) L': 'stride_length_cm_left',
 'Stride Length(cm) R': 'stride_length_cm_right',
 'HH Base Support (cm) L': 'hh_base_support_cm_left',
 'HH Base Support (cm) R': 'hh_base_support_cm_right',
 'Swing % of Cycle L': 'swing_pct_of_cycle_left',
 'Swing % of Cycle R': 'swing_pct_of_cycle_right',
 'Swing Time(sec) L': 'swing_time_sec_left',
 'Swing Time(sec) R': 'swing_time_sec_right',
 'Stance % of Cycle L': 'stance_pct_of_cycle_left',
 'Stance % of Cycle R': 'stance_pct_of_cycle_right',
 'Stance Time(sec)  L': 'stance_time_sec_left',
 'Stance Time(sec)  R': 'stance_time_sec_right',
 'Single Supp % Cycle L': 'single_supp_pct_cycle_left',
 'Single Supp % Cycle R': 'single_supp_pct_cycle_right',
 'Single Supp. Time(sec) L': 'single_supp_time_sec_left',
 'Single Supp. Time(sec) R': 'single_supp_time_sec_right',
 'Double Supp % Cycle L': 'double_supp_pct_cycle_left',
 'Double Supp % Cycle R': 'double_supp_pct_cycle_right',
 'Double Supp. Time(sec) L': 'double_supp_time_sec_left',
 'Double Supp. Time(sec) R': 'double_supp_time_sec_right',
 'Step Time Differential': 'step_time_differential',
 'Step Length Differential': 'step_length_differetial',
 'Cycle Time Differential': 'cycle_time_differential',
 'Functional Amb. Profile': 'functional_amb_profile',
 'Treatment Count': 'treatment_count',
 'Footfalls': 'footfalls',
 'Comments': 'comments',
 'Normalized Velocity  ': 'normalized_velocity',
 'Leg Length (cm) L': 'leg_length_cm_left',
 'Leg Length (cm) R': 'leg_length_cm_right',
 'Number of Passes': 'number_of_passes',
 'Ambulatory Devices': 'ambulatory_devices',
 'Ambulatory Aids': 'ambulatory_aids',
 'User': 'user',
 'Toe In / Out L': 'toe_in_out_left',
 'Toe In / Out R': 'toe_in_out_right',
 'Heel Off On Time L': 'heel_off_on_time_left',
 'Heel Off On Time R': 'heel_off_on_time_right',
 'Heel Off On Perc L': 'heel_off_on_perc_left',
 'Heel Off On Perc R': 'heel_off_on_perc_right',
 'Double Support Load Time L': 'double_support_load_time_left',
 'Double Support Load Time R': 'double_support_load_time_right',
 'Double Support Load %GC L': 'double_support_load_pct_gc_left',
 'Double Support Load %GC R': 'double_support_load_pct_gc_right',
 'Double Support Unload Time L': 'double_support_unload_time_left',
 'Double Support Unload Time R': 'double_support_unload_time_right',
 'Double Support Unload %GC L': 'double_support_unload_pct_gc_left',
 'Double Support Unload %GC R': 'double_support_unload_pct_gc_right',
 'Asst Ortho etc 1': 'asst_ortho_etc_1',
 'Asst Ortho etc  2': 'asst_ortho_etc_2',
 'Asst Ortho etc 3': 'asst_ortho_etc_3',
 'Asst Ortho etc 4': 'asst_ortho_etc_4',
 'Asst Ortho etc 5': 'asst_ortho_etc_5',
 'Type of Test': 'type_of_test',
 'Software Version': 'software_version',
 'Number of Pads': 'number_of_pads',
 'Normal Group Code': 'normal_group_code',
 'Standard Walk Steps': 'standard_walk_steps',
 'Standard Amb Time': 'standard_amb_time',
 'Stride Velocity Left': 'stride_velocity_left',
 'Stride Velocity Right': 'stride_velocity_right',
 'Shoe Flag': 'shoe_flag',
 'Expected Foot Length': 'expected_foot_length',
 'Expected Foot Width': 'expected_foot_width',
 'Foot Length Left': 'foot_length_left',
 'Foot Width Left': 'foot_width_left',
 'Foot Length Right': 'foot_length_right',
 'Foot Width Right': 'foot_width_right',
 'Step Len Std Dev Left': 'step_len_std_dev_left',
 'Step Len Std Dev Right': 'step_len_std_dev_right',
 'Step Time Std Dev Left': 'step_time_std_dev_left',
 'Step Time Std Dev Right': 'step_time_std_dev_right',
 'Stride Length Std Dev Left': 'stride_length_std_dev_left',
 'Stride Length Std Dev Right': 'stride_length_std_dev_right',
 'Stride Time Std Dev Left': 'stride_time_std_dev_left',
 'Stride Time Std Dev Right': 'stride_time_std_dev_right',
 'Swing Time Std Dev Left': 'swing_time_std_dev_left',
 'Swing Time Std Dev Right!': 'swing_time_std_dev_right',
 'Stance Time Std Dev Left': 'stance_time_std_dev_left',
 'Stance Time Std Dev Right': 'stance_time_std_dev_right',
 'Stride Velocity Std Dev Left': 'stride_velocity_std_dev_left',
 'Stride Velocity Std Dev Right': 'stride_velocity_std_dev_right',
 'Single Supp Time Std Dev Left': 'single_supp_time_std_dev_left',
 'Single Supp Time Std Dev Right': 'single_supp_time_std_dev_right',
 'Double Supp Time Std Dev Left': 'double_supp_time_std_dev_left',
 'Double Supp Time Std Dev Right': 'double_supp_time_std_dev_right',
 'Heel Off On Std Dev Left': 'heel_off_on_std_dev_left',
 'Heel Off On Std Dev Right': 'heel_off_on_std_dev_right',
 'Supp Base Std Dev Left': 'supp_base_std_dev_left',
 'Supp Base Std Dev Right': 'supp_base_std_dev_right',
 'Foot Length Std Dev Left': 'foot_length_std_dev_left',
 'Foot Length Std Dev Right': 'foot_length_std_dev_right',
 'Foot Width Std Dev Left': 'foot_width_std_dev_left',
 'Foot Width Std Dev Right': 'foot_width_std_dev_right',
 'Computer Time (MSec)': 'computer_time_msec',
 'Trigger 1 0': 'trigger_1_0',
 'Trigger 1 1': 'trigger_1_1',
 'Trigger 2 0': 'trigger_2_0',
 'Trigger 2 1': 'trigger_2_1',
 'Trigger 1 E': 'trigger_1_e',
 'Trigger 1 E 1': 'trigger_1_e_1',
 'Trigger 2 E': 'trigger_2_e',
 'Trigger 2 E 1': 'trigger_2_e_1',
 'Inclinometer1': 'inclinometer1',
 'Inclin_Avg_Tilt_LR': 'inclin_avg_tilt_lr',
 'Inclin_Avg_Tilt_FB': 'inclin_avg_tilt_fb',
 'Inclin_Min_Tilt_LR': 'inclin_min_tilt_lr',
 'Inclin_Max_Tilt_LR': 'inclin_max_tilt_lr',
 'Inclin_Max_Tilt_FB': 'inclin_max_tilt_fb',
 'Inclin_Min_Tilt_FB': 'inclin_min_tilt_fb',
 'Inclin_Veloc_Tilt_LR': 'inclin_veloc_tilt_lr',
 'Inclin_Veloc_Tilt_FB': 'inclin_veloc_tilt_fb',
 'Inclin_SD_Tilt_LR': 'inclin_sd_tilt_lr',
 'Inclin_SD_Tilt_FB': 'inclin_sd_tilt_fb',
 'Inclinometer2': 'inclinometer2',
 'Inclin2_Avg_Tilt_LR': 'inclin2_avg_tilt_lr',
 'Inclin2_Avg_Tilt_FB': 'inclin2_avg_tilt_fb',
 'Inclin2_Min_Tilt_LR': 'inclin2_min_tilt_lr',
 'Inclin2_Max_Tilt_LR': 'inclin2_max_tilt_lr'}

In [112]:
def grGetTestRecords(filename, old_columns, new_columns):
    if filename.lower().endswith("csv"):
        df = pd.read_csv(filename) 
    elif filename.lower().endswith("xlsx"):
        df = pd.read_excel(filename)
    else:
        raise RuntimeError("Unknown filetype: " + filename)
        
    dict = {old_columns[i]: new_columns[i] for i in range(len(old_columns))}
    df2 = df[old_columns]
    df3 = df2.rename(columns=dict)
    df4 = df3[~df3['test_record_num'].isna()].copy()
    
    # get FXS id
    last = next(filter(lambda id: not pd.isna(id), df['Last Name']), None)
    if last == None:
        last = 0
        print("WARNING: No FXS ID found.")
    
    # don't forget to add key column
    # TODO: HARD CODED KEY COLUMN NAME study_id
    df4.insert(0, "study_id", last)
    
    # and insert the filename
    df4.insert(1, 'aa_input_filename', os.path.basename(filename))
    
    
    return df4

In [102]:
df=pd.read_excel('/Users/dan/rivera/tmp/100398-100_05_23_19.xlsx')
df.head()

,Research Reference,Pt Record #,Patient Id Number,Last Name,First Name,Leg Length Left,Leg Length Right,Test Record #,Pt Record #.1,Date / Time of Test,...,Stride Width,Heel On,Heel Off,Mid On,Mid Off,Toe On,Toe Off,Heel off/on,Double Support Loading,Double Support Unloading
0,NaN,89.0,,100398-100,100398-100,87.5,87.5,3.0,89.0,2019-05-23 14:52:22,...,0.000,4.600,5.017,4.684,5.150,4.650,5.250,0.108,0.000,0.000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,13.691,5.125,5.592,5.192,5.750,5.209,5.834,0.108,0.125,0.134
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,16.087,5.700,6.125,5.809,6.259,5.750,6.342,0.092,0.134,0.125
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,12.787,6.217,6.659,6.325,6.825,6.275,6.934,0.133,0.125,0.142
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,9.612,6.792,7.250,6.892,7.367,6.859,7.467,0.084,0.142,0.134

In [103]:
df.columns

Index(['Research Reference', 'Pt Record #', 'Patient Id Number', 'Last Name',
       'First Name  ', 'Leg Length Left', 'Leg Length Right', 'Test Record #',
       'Pt Record #.1', 'Date / Time of Test',
       ...
       'Stride Width', 'Heel On', 'Heel Off', 'Mid On', 'Mid Off', 'Toe On',
       'Toe Off ', 'Heel off/on', 'Double Support Loading ',
       'Double Support Unloading '],
      dtype='object', length=185)

In [113]:
tests = grGetTestRecords('/Users/dan/rivera/tmp/100398-100_05_23_19.xlsx', old_cols, new_cols)

In [105]:
tests = grGetTestRecords('/Users/dan/rivera/data/full-single-2.csv', old_cols, new_cols)

In [114]:
tests.head()

,study_id,aa_input_filename,aa_fn,aa_ln,test_record_num,pt_record_num,date_time_of_test,distance,ambulation_time,velocity,...,inclin_min_tilt_fb,inclin_veloc_tilt_lr,inclin_veloc_tilt_fb,inclin_sd_tilt_lr,inclin_sd_tilt_fb,inclinometer2,inclin2_avg_tilt_lr,inclin2_avg_tilt_fb,inclin2_min_tilt_lr,inclin2_max_tilt_lr
0,100398-100,100398-100_05_23_19.xlsx,100398-100,100398-100,3.0,89.0,2019-05-23 14:52:22,2230.75,25.74,86.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,100398-100,100398-100_05_23_19.xlsx,NaN,NaN,2.0,NaN,2019-05-23 14:57:31,2275.98,26.38,86.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105,100398-100,100398-100_05_23_19.xlsx,NaN,NaN,1.0,NaN,2019-05-23 15:01:27,2280.14,31.76,71.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
first = next(filter(lambda id: not pd.isna(id), df['Last Name']), None)
print(first)
second = next(filter(lambda id: id==999, df['Last Name']), None)
print(second)

316.0
None

In [24]:
x1 = pd.read_excel('/Users/dan/rivera/tmp/100398-100_05_23_19.xlsx')

In [27]:
x1.head()

,Research Reference,Pt Record #,Patient Id Number,Last Name,First Name,Leg Length Left,Leg Length Right,Test Record #,Pt Record #.1,Date / Time of Test,...,Stride Width,Heel On,Heel Off,Mid On,Mid Off,Toe On,Toe Off,Heel off/on,Double Support Loading,Double Support Unloading
0,NaN,89.0,,100398-100,100398-100,87.5,87.5,3.0,89.0,2019-05-23 14:52:22,...,0.000,4.600,5.017,4.684,5.150,4.650,5.250,0.108,0.000,0.000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,13.691,5.125,5.592,5.192,5.750,5.209,5.834,0.108,0.125,0.134
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,16.087,5.700,6.125,5.809,6.259,5.750,6.342,0.092,0.134,0.125
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,12.787,6.217,6.659,6.325,6.825,6.275,6.934,0.133,0.125,0.142
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,9.612,6.792,7.250,6.892,7.367,6.859,7.467,0.084,0.142,0.134

In [26]:
x1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Columns: 185 entries, Research Reference to Double Support Unloading
dtypes: datetime64[ns](2), float64(177), object(6)
memory usage: 247.3+ KB

In [23]:
import sys
print(sys.version)

3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]

In [28]:
import os

In [115]:
bigdf = None
folder = '/Users/dan/rivera/tmp'
for f in os.scandir(folder):
    if (f.is_file() and f.name.endswith("xlsx")):
        df = grGetTestRecords(os.path.join(folder, f.name), old_cols, new_cols)
        if bigdf is None:
            bigdf = df
        else:
            bigdf = pd.concat((bigdf, df))

In [108]:
bigdf

,study_id,aa_fn,aa_ln,test_record_num,pt_record_num,date_time_of_test,distance,ambulation_time,velocity,step_count,...,inclin_min_tilt_fb,inclin_veloc_tilt_lr,inclin_veloc_tilt_fb,inclin_sd_tilt_lr,inclin_sd_tilt_fb,inclinometer2,inclin2_avg_tilt_lr,inclin2_avg_tilt_fb,inclin2_min_tilt_lr,inclin2_max_tilt_lr
0,500011-521,500011-521,500011-521,3.0,126.0,2020-02-06 12:34:27,2347.55,39.58,59.3,67.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,500011-521,NaN,NaN,2.0,NaN,2020-02-06 12:38:21,2239.87,39.22,57.1,63.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144,500011-521,NaN,NaN,1.0,NaN,2020-02-06 12:42:03,2267.82,53.68,42.2,65.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,500011-327,500011-327,500011-327,3.0,151.0,2021-09-22 10:30:04,2289.33,39.92,57.3,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,500011-327,NaN,NaN,2.0,NaN,2021-09-22 10:26:33,2170.58,26.96,80.5,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,75.0,NaN,NaN,4.0,NaN,2019-11-04 13:40:55,2132.67,14.26,149.6,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66,75.0,NaN,NaN,1.0,NaN,2019-11-04 13:44:47,2161.09,14.18,152.4,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,487.0,500011-138,487.0,3.0,116.0,2019-11-26 11:40:49,2172.91,14.70,147.8,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,487.0,NaN,NaN,2.0,NaN,2019-11-26 11:45:09,2097.66,15.23,137.7,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,487.0,NaN,NaN,1.0,NaN,2019-11-26 11:47:39,2184.66,15.89,137.5,32.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [110]:
bigdf[bigdf.study_id==75.0]

,study_id,aa_fn,aa_ln,test_record_num,pt_record_num,date_time_of_test,distance,ambulation_time,velocity,step_count,...,inclin_min_tilt_fb,inclin_veloc_tilt_lr,inclin_veloc_tilt_fb,inclin_sd_tilt_lr,inclin_sd_tilt_fb,inclinometer2,inclin2_avg_tilt_lr,inclin2_avg_tilt_fb,inclin2_min_tilt_lr,inclin2_max_tilt_lr
0,75.0,107867-100,75.0,5.0,111.0,2019-11-04 13:37:58,1929.07,12.18,158.4,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,75.0,NaN,NaN,4.0,NaN,2019-11-04 13:40:55,2132.67,14.26,149.6,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66,75.0,NaN,NaN,1.0,NaN,2019-11-04 13:44:47,2161.09,14.18,152.4,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
def is_float(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

In [62]:
def is_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

In [69]:
is_int('1.0')

False